# This is a basic workflow to help you get started with Actions

name: Generate Indices Zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate indices.zip
      run: |
        zip -r indices.zip planetes/*
        
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: indices-archive
        path: indices.zip
